// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using  Vito.Transverse.Identity.Infrastructure.DataBaseContext;

#nullable disable

namespace  Vito.Transverse.Identity.Infrastructure.Migrations
{
    [DbContext(typeof(DataBaseServiceContext))]
    [Migration("20251028231459_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.ActivityLog", b =>
                {
                    b.Property<long>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TraceId"));

                    b.Property<long>("ActionTypeFk")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<string>("CultureId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EndPointUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Referer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("UserFk")
                        .HasColumnType("bigint");

                    b.HasKey("TraceId")
                        .HasName("PK_UserTraces");

                    b.HasIndex("ActionTypeFk");

                    b.HasIndex("UserFk");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Application", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ApplicationClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ApplicationSecret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DescriptionTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id")
                        .HasName("PK_Applications_1");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.ApplicationLicenseType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DescriptionTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("LicenseFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("ApplicationLicenseTypes");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.ApplicationOwner", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<long?>("ApplicationLicenseTypeFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationFk");

                    b.HasIndex("ApplicationLicenseTypeFk");

                    b.HasIndex("CompanyFk");

                    b.ToTable("ApplicationOwners");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.AuditRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuditChanges")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuditEntityIndex")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long>("AuditTypeFk")
                        .HasColumnType("bigint");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CultureFk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EndPointUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("EntityFk")
                        .HasColumnType("bigint");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Referer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("UserFk")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuditTypeFk");

                    b.HasIndex("CompanyFk");

                    b.HasIndex("EntityFk");

                    b.HasIndex("UserFk");

                    b.ToTable("AuditRecords");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Company", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("CompanyClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CompanySecret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CountryFk")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DefaultCultureFk")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("DescriptionTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemCompany")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CountryFk");

                    b.HasIndex("DefaultCultureFk");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.CompanyEntityAudit", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("AuditTypeFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<long>("EntityFk")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<long?>("UpdatedByUserFk")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AuditTypeFk");

                    b.HasIndex("CompanyFk");

                    b.HasIndex("EntityFk");

                    b.ToTable("CompanyEntityAudits");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.CompanyMembership", b =>
                {
                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("MembershipTypeFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("CompanyFk", "ApplicationFk")
                        .HasName("PK_CompanyApplications");

                    b.HasIndex("ApplicationFk");

                    b.HasIndex("MembershipTypeFk");

                    b.HasIndex(new[] { "Id" }, "IX_CompanyMemberships")
                        .IsUnique();

                    b.ToTable("CompanyMemberships");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.CompanyMembershipPermission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyMembershipFk")
                        .HasColumnType("bigint");

                    b.Property<long?>("ComponentFk")
                        .HasColumnType("bigint");

                    b.Property<long>("EndpointFk")
                        .HasColumnType("bigint");

                    b.Property<long>("ModuleFk")
                        .HasColumnType("bigint");

                    b.Property<string>("PropertyValue")
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.HasKey("Id")
                        .HasName("PK_CompanyMembershipPermissions_1");

                    b.HasIndex(new[] { "CompanyMembershipFk" }, "IX_CompanyMembershipPermissions");

                    b.ToTable("CompanyMembershipPermissions");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Component", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<string>("DefaultPropertyValue")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("DescriptionTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long>("EndpointFk")
                        .HasColumnType("bigint");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("ObjectPropertyName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long?>("PositionIndex")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_EndpointComponents");

                    b.HasIndex("ApplicationFk");

                    b.HasIndex("EndpointFk");

                    b.ToTable("Components");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<int?>("UtcHoursDifference")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Culture", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("CountryFk")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageFk")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.HasIndex("CountryFk");

                    b.HasIndex("LanguageFk");

                    b.ToTable("Cultures");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.CultureTranslation", b =>
                {
                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<string>("CultureFk")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("TranslationKey")
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("TranslationValue")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("ApplicationFk", "CultureFk", "TranslationKey");

                    b.HasIndex("CultureFk");

                    b.HasIndex(new[] { "ApplicationFk" }, "IX_CultureTranslations");

                    b.ToTable("CultureTranslations");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Endpoint", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<string>("DescriptionTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsApi")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<long>("ModuleFk")
                        .HasColumnType("bigint");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long?>("PositionIndex")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_EndpointsModules");

                    b.HasIndex("ApplicationFk");

                    b.HasIndex("ModuleFk");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Entity", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemEntity")
                        .HasColumnType("bit");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.HasKey("Id")
                        .HasName("PK_AuditEntities");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSystemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id")
                        .HasName("PK_ListItemGroup");

                    b.ToTable("GeneralTypeGroups");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("ListItemGroupFk")
                        .HasColumnType("bigint");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_ListItems");

                    b.HasIndex("ListItemGroupFk");

                    b.ToTable("GeneralTypeItems");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.MembershipType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DescriptionTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Memberships");

                    b.ToTable("MembershipTypes");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.MembersipPriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("LastIncreasePercentage")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("MembershipTypeFk")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("MembershipTypeFk");

                    b.ToTable("MembersipPriceHistory", (string)null);
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Module", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<string>("DescriptionTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsApi")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long?>("PositionIndex")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationFk");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bcc")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("BCC");

                    b.Property<string>("Cc")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("CC");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CultureFk")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<long>("NotificationTemplateGroupFk")
                        .HasColumnType("bigint");

                    b.Property<long>("NotificationTypeFk")
                        .HasColumnType("bigint");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id")
                        .HasName("PK_NotificationTraces");

                    b.HasIndex("CompanyFk");

                    b.HasIndex("CultureFk");

                    b.HasIndex("NotificationTypeFk");

                    b.HasIndex("NotificationTemplateGroupFk", "CultureFk");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.NotificationTemplate", b =>
                {
                    b.Property<long>("NotificationTemplateGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("CultureFk")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsHtml")
                        .HasColumnType("bit");

                    b.Property<string>("MessageTemplateText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("SubjectTemplateText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationTemplateGroupId", "CultureFk");

                    b.HasIndex("CultureFk");

                    b.ToTable("NotificationTemplates");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Picture", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("BinaryPicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<long>("EntityFk")
                        .HasColumnType("bigint");

                    b.Property<long>("FileTypeFk")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long>("PictureCategoryFk")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PictureSize")
                        .HasColumnType("decimal(18, 5)");

                    b.HasKey("Id");

                    b.HasIndex("EntityFk");

                    b.HasIndex("FileTypeFk");

                    b.HasIndex("PictureCategoryFk");

                    b.HasIndex(new[] { "CompanyFk", "Name" }, "IX_Pictures");

                    b.ToTable("Pictures");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DescriptionTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.HasKey("Id")
                        .HasName("PK_Roles_1");

                    b.HasIndex("ApplicationFk");

                    b.HasIndex("CompanyFk");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long?>("ComponentFk")
                        .HasColumnType("bigint");

                    b.Property<long?>("EndpointFk")
                        .HasColumnType("bigint");

                    b.Property<long>("ModuleFk")
                        .HasColumnType("bigint");

                    b.Property<string>("PropertyValue")
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long>("RoleFk")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_UserRolePermissions");

                    b.HasIndex("ComponentFk");

                    b.HasIndex("EndpointFk");

                    b.HasIndex("ModuleFk");

                    b.HasIndex("RoleFk");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Sequence", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("SequenceIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("SequenceNameFormat")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long>("SequenceTypeFk")
                        .HasColumnType("bigint");

                    b.Property<string>("TextFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationFk");

                    b.HasIndex("CompanyFk");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("ActivationEmailSent")
                        .HasColumnType("bit");

                    b.Property<Guid>("ActivationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("EmailValidated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LockedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("RequirePasswordChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<long?>("UpdatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyFk");

                    b.ToTable("Users");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.UserRole", b =>
                {
                    b.Property<long>("UserFk")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleFk")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserFk", "RoleFk");

                    b.HasIndex("RoleFk");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.VwCompanyUserRole", b =>
                {
                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar(130)");

                    b.Property<bool>("UserRoleIsActive")
                        .HasColumnType("bit");

                    b.ToTable((string)null);

                    b.ToView("Vw_CompanyUserRoles", (string)null);
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.VwGetAllCompanyPermission", b =>
                {
                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ApplicationIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyMembershipFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyMembershipPermissionsId")
                        .HasColumnType("bigint");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long?>("ComponentFk")
                        .HasColumnType("bigint");

                    b.Property<long>("EndpointId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EndpointIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ModuleIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.ToTable((string)null);

                    b.ToView("Vw_GetAllCompanyPermissions", (string)null);
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.VwGetAuditRecord", b =>
                {
                    b.Property<string>("AuditChanges")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("AuditTypeFk")
                        .HasColumnType("bigint");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CultureFk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("EntityFk")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("Expr1")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<bool>("IsSystemEntity")
                        .HasColumnType("bit");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long>("UserFk")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.ToTable((string)null);

                    b.ToView("Vw_GetAuditRecords", (string)null);
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.VwGetCompanyMembership", b =>
                {
                    b.Property<Guid>("ApplicationClient")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ApplicationIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<Guid>("ApplicationSecret")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyClient")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<bool>("CompanyIsActive")
                        .HasColumnType("bit");

                    b.Property<long>("CompanyMemberShipId")
                        .HasColumnType("bigint");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<Guid>("CompanySecret")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryFk")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("DefaultCultureFk")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsSystemCompany")
                        .HasColumnType("bit");

                    b.Property<long>("MembershipTypeFk")
                        .HasColumnType("bigint");

                    b.Property<bool>("MembershipTypeIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MembershipTypeName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.ToTable((string)null);

                    b.ToView("Vw_GetCompanyMemberships", (string)null);
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.VwGetDatabaseTable", b =>
                {
                    b.Property<string>("Expr1")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("name");

                    b.Property<long?>("NameRowNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("name_row_number");

                    b.ToTable((string)null);

                    b.ToView("Vw_GetDatabaseTables", (string)null);
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.VwGetGeneralTypeItemWithGroup", b =>
                {
                    b.Property<bool>("GeneralTypeGroup")
                        .HasColumnType("bit");

                    b.Property<long>("GeneralTypeGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("GeneralTypeGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("GeneralTypeItemId")
                        .HasColumnType("bigint");

                    b.Property<int?>("GeneralTypeItemIndex")
                        .HasColumnType("int");

                    b.Property<bool>("GeneralTypeItemIsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("GeneralTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSystemType")
                        .HasColumnType("bit");

                    b.ToTable((string)null);

                    b.ToView("Vw_GetGeneralTypeItemWithGroups", (string)null);
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.VwGetRolePermission", b =>
                {
                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ApplicationIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long?>("ComponentFk")
                        .HasColumnType("bigint");

                    b.Property<long>("EndpointId")
                        .HasColumnType("bigint");

                    b.Property<bool>("EndpointIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<string>("EndpointUrl")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ModuleIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long>("RoleFk")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(85)
                        .IsUnicode(false)
                        .HasColumnType("varchar(85)");

                    b.Property<long>("RolePermissionsId")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("Vw_GetRolePermissions", (string)null);
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.ActivityLog", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeItem", "ActionTypeFkNavigation")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ActionTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_ActivityLogs_ListItems");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.User", "UserFkNavigation")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserFk")
                        .IsRequired()
                        .HasConstraintName("FK_ActivityLogs_Users");

                    b.Navigation("ActionTypeFkNavigation");

                    b.Navigation("UserFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.ApplicationOwner", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Application", "ApplicationFkNavigation")
                        .WithMany("ApplicationOwners")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationOwners_Applications");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.ApplicationLicenseType", "ApplicationLicenseTypeFkNavigation")
                        .WithMany("ApplicationOwners")
                        .HasForeignKey("ApplicationLicenseTypeFk")
                        .HasConstraintName("FK_ApplicationOwners_ApplicationLicenseTypes");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Company", "CompanyFkNavigation")
                        .WithMany("ApplicationOwners")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationOwners_Companies");

                    b.Navigation("ApplicationFkNavigation");

                    b.Navigation("ApplicationLicenseTypeFkNavigation");

                    b.Navigation("CompanyFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.AuditRecord", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeItem", "AuditTypeFkNavigation")
                        .WithMany("AuditRecords")
                        .HasForeignKey("AuditTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_AuditRecords_GeneralTypeItems");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Company", "CompanyFkNavigation")
                        .WithMany("AuditRecords")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_AuditRecords_Companies");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Entity", "EntityFkNavigation")
                        .WithMany("AuditRecords")
                        .HasForeignKey("EntityFk")
                        .IsRequired()
                        .HasConstraintName("FK_AuditRecords_Entities");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.User", "UserFkNavigation")
                        .WithMany("AuditRecords")
                        .HasForeignKey("UserFk")
                        .IsRequired()
                        .HasConstraintName("FK_AuditRecords_Users");

                    b.Navigation("AuditTypeFkNavigation");

                    b.Navigation("CompanyFkNavigation");

                    b.Navigation("EntityFkNavigation");

                    b.Navigation("UserFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Company", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Country", "CountryFkNavigation")
                        .WithMany("Companies")
                        .HasForeignKey("CountryFk")
                        .IsRequired()
                        .HasConstraintName("FK_Companies_Countries");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Culture", "DefaultCultureFkNavigation")
                        .WithMany("Companies")
                        .HasForeignKey("DefaultCultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_Companies_Cultures");

                    b.Navigation("CountryFkNavigation");

                    b.Navigation("DefaultCultureFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.CompanyEntityAudit", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeItem", "AuditTypeFkNavigation")
                        .WithMany("CompanyEntityAudits")
                        .HasForeignKey("AuditTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyEntityAudits_GeneralTypeItems");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Company", "CompanyFkNavigation")
                        .WithMany("CompanyEntityAudits")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyEntityAudits_Companies");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Entity", "EntityFkNavigation")
                        .WithMany("CompanyEntityAudits")
                        .HasForeignKey("EntityFk")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyEntityAudits_Entities");

                    b.Navigation("AuditTypeFkNavigation");

                    b.Navigation("CompanyFkNavigation");

                    b.Navigation("EntityFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.CompanyMembership", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Application", "ApplicationFkNavigation")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyMemberships_Applications");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Company", "CompanyFkNavigation")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyMemberships_Companies");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.MembershipType", "MembershipTypeFkNavigation")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("MembershipTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyMemberships_Memberships");

                    b.Navigation("ApplicationFkNavigation");

                    b.Navigation("CompanyFkNavigation");

                    b.Navigation("MembershipTypeFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.CompanyMembershipPermission", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.CompanyMembership", "CompanyMembershipFkNavigation")
                        .WithMany("CompanyMembershipPermissions")
                        .HasForeignKey("CompanyMembershipFk")
                        .HasPrincipalKey("Id")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyMembershipPermissions_CompanyMemberships");

                    b.Navigation("CompanyMembershipFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Component", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Application", "ApplicationFkNavigation")
                        .WithMany("Components")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_Components_Applications");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Endpoint", "EndpointFkNavigation")
                        .WithMany("Components")
                        .HasForeignKey("EndpointFk")
                        .IsRequired()
                        .HasConstraintName("FK_EndpointComponents_ModuleEndpoints");

                    b.Navigation("ApplicationFkNavigation");

                    b.Navigation("EndpointFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Culture", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Country", "CountryFkNavigation")
                        .WithMany("Cultures")
                        .HasForeignKey("CountryFk")
                        .IsRequired()
                        .HasConstraintName("FK_Cultures_Countries");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Language", "LanguageFkNavigation")
                        .WithMany("Cultures")
                        .HasForeignKey("LanguageFk")
                        .IsRequired()
                        .HasConstraintName("FK_Cultures_Languages");

                    b.Navigation("CountryFkNavigation");

                    b.Navigation("LanguageFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.CultureTranslation", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Application", "ApplicationFkNavigation")
                        .WithMany("CultureTranslations")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_CultureTranslations_Applications");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Culture", "CultureFkNavigation")
                        .WithMany("CultureTranslations")
                        .HasForeignKey("CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_CultureTranslations_Cultures");

                    b.Navigation("ApplicationFkNavigation");

                    b.Navigation("CultureFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Endpoint", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Application", "ApplicationFkNavigation")
                        .WithMany("Endpoints")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_Endpoints_Applications");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Module", "ModuleFkNavigation")
                        .WithMany("Endpoints")
                        .HasForeignKey("ModuleFk")
                        .IsRequired()
                        .HasConstraintName("FK_ModuleEndpoint_Modules");

                    b.Navigation("ApplicationFkNavigation");

                    b.Navigation("ModuleFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeItem", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeGroup", "ListItemGroupFkNavigation")
                        .WithMany("GeneralTypeItems")
                        .HasForeignKey("ListItemGroupFk")
                        .IsRequired()
                        .HasConstraintName("FK_ListItems_ListItemGroup");

                    b.Navigation("ListItemGroupFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.MembersipPriceHistory", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.MembershipType", "MembershipTypeFkNavigation")
                        .WithMany("MembersipPriceHistories")
                        .HasForeignKey("MembershipTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_MembersipPriceHistory_Memberships");

                    b.Navigation("MembershipTypeFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Module", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Application", "ApplicationFkNavigation")
                        .WithMany("Modules")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_Modules_Applications");

                    b.Navigation("ApplicationFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Notification", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Company", "CompanyFkNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Companies");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Culture", "CultureFkNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_NotificationTraces_Cultures");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeItem", "NotificationTypeFkNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_ListItems");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.NotificationTemplate", "NotificationTemplate")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTemplateGroupFk", "CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_NotificationTemplates");

                    b.Navigation("CompanyFkNavigation");

                    b.Navigation("CultureFkNavigation");

                    b.Navigation("NotificationTemplate");

                    b.Navigation("NotificationTypeFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.NotificationTemplate", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Culture", "CultureFkNavigation")
                        .WithMany("NotificationTemplates")
                        .HasForeignKey("CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_NotificationTemplates_Cultures");

                    b.Navigation("CultureFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Picture", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Company", "CompanyFkNavigation")
                        .WithMany("Pictures")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Pictures_Companies");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Entity", "EntityFkNavigation")
                        .WithMany("Pictures")
                        .HasForeignKey("EntityFk")
                        .IsRequired()
                        .HasConstraintName("FK_Pictures_Entities");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeItem", "FileTypeFkNavigation")
                        .WithMany("PictureFileTypeFkNavigations")
                        .HasForeignKey("FileTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_Pictures_GeneralTypeItems");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeItem", "PictureCategoryFkNavigation")
                        .WithMany("PicturePictureCategoryFkNavigations")
                        .HasForeignKey("PictureCategoryFk")
                        .IsRequired()
                        .HasConstraintName("FK_Pictures_GeneralTypeItems1");

                    b.Navigation("CompanyFkNavigation");

                    b.Navigation("EntityFkNavigation");

                    b.Navigation("FileTypeFkNavigation");

                    b.Navigation("PictureCategoryFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Role", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Application", "ApplicationFkNavigation")
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_Roles_Applications");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Company", "CompanyFkNavigation")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Roles_Companies");

                    b.Navigation("ApplicationFkNavigation");

                    b.Navigation("CompanyFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.RolePermission", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Component", "ComponentFkNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ComponentFk")
                        .HasConstraintName("FK_UserRolePermissions_Components");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Endpoint", "EndpointFkNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("EndpointFk")
                        .HasConstraintName("FK_UserRolePermissions_Endpoints");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Module", "ModuleFkNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ModuleFk")
                        .IsRequired()
                        .HasConstraintName("FK_UserRolePermissions_Modules");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Role", "RoleFkNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleFk")
                        .IsRequired()
                        .HasConstraintName("FK_RolePermissions_Roles");

                    b.Navigation("ComponentFkNavigation");

                    b.Navigation("EndpointFkNavigation");

                    b.Navigation("ModuleFkNavigation");

                    b.Navigation("RoleFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Sequence", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Application", "ApplicationFkNavigation")
                        .WithMany("Sequences")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_Sequences_Applications");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Company", "CompanyFkNavigation")
                        .WithMany("Sequences")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Sequences_Companies");

                    b.Navigation("ApplicationFkNavigation");

                    b.Navigation("CompanyFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.User", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Company", "CompanyFkNavigation")
                        .WithMany("Users")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Companies");

                    b.Navigation("CompanyFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.UserRole", b =>
                {
                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.Role", "RoleFkNavigation")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleFk")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Roles");

                    b.HasOne(" Vito.Transverse.Identity.Infrastructure.Models.User", "UserFkNavigation")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserFk")
                        .IsRequired()
                        .HasConstraintName("FK_UserRoles_Users");

                    b.Navigation("RoleFkNavigation");

                    b.Navigation("UserFkNavigation");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Application", b =>
                {
                    b.Navigation("ApplicationOwners");

                    b.Navigation("CompanyMemberships");

                    b.Navigation("Components");

                    b.Navigation("CultureTranslations");

                    b.Navigation("Endpoints");

                    b.Navigation("Modules");

                    b.Navigation("Roles");

                    b.Navigation("Sequences");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.ApplicationLicenseType", b =>
                {
                    b.Navigation("ApplicationOwners");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Company", b =>
                {
                    b.Navigation("ApplicationOwners");

                    b.Navigation("AuditRecords");

                    b.Navigation("CompanyEntityAudits");

                    b.Navigation("CompanyMemberships");

                    b.Navigation("Notifications");

                    b.Navigation("Pictures");

                    b.Navigation("Roles");

                    b.Navigation("Sequences");

                    b.Navigation("Users");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.CompanyMembership", b =>
                {
                    b.Navigation("CompanyMembershipPermissions");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Component", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Country", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Cultures");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Culture", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("CultureTranslations");

                    b.Navigation("NotificationTemplates");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Endpoint", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Entity", b =>
                {
                    b.Navigation("AuditRecords");

                    b.Navigation("CompanyEntityAudits");

                    b.Navigation("Pictures");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeGroup", b =>
                {
                    b.Navigation("GeneralTypeItems");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.GeneralTypeItem", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("AuditRecords");

                    b.Navigation("CompanyEntityAudits");

                    b.Navigation("Notifications");

                    b.Navigation("PictureFileTypeFkNavigations");

                    b.Navigation("PicturePictureCategoryFkNavigations");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Language", b =>
                {
                    b.Navigation("Cultures");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.MembershipType", b =>
                {
                    b.Navigation("CompanyMemberships");

                    b.Navigation("MembersipPriceHistories");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Module", b =>
                {
                    b.Navigation("Endpoints");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.NotificationTemplate", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity(" Vito.Transverse.Identity.Infrastructure.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("AuditRecords");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
