// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vito.Transverse.Identity.DAL.DataBaseContext;

#nullable disable

namespace Vito.Transverse.Identity.DAL.Migrations
{
    [DbContext(typeof(DataBaseServiceContext))]
    [Migration("20250506100133_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ActivityLog", b =>
                {
                    b.Property<long>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TraceId"));

                    b.Property<long>("ActionTypeFk")
                        .HasColumnType("bigint");

                    b.Property<string>("AddtionalInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<string>("CultureId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RequestEndpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<long>("UserFk")
                        .HasColumnType("bigint");

                    b.HasKey("TraceId")
                        .HasName("PK_UserTraces");

                    b.HasIndex("ActionTypeFk");

                    b.HasIndex("UserFk");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Application", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ApplicationClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("ApplicationSecret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_Applications_1");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Company", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("CompanyClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CompanySecret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("CountryFk")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DefaultCultureFk")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemCompany")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CountryFk");

                    b.HasIndex("DefaultCultureFk");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.CompanyMembership", b =>
                {
                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("MembershipTypeFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("CompanyFk", "ApplicationFk")
                        .HasName("PK_CompanyApplications");

                    b.HasIndex("ApplicationFk");

                    b.HasIndex("MembershipTypeFk");

                    b.HasIndex(new[] { "Id" }, "IX_CompanyMemberships")
                        .IsUnique();

                    b.ToTable("CompanyMemberships");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.CompanyMembershipPermission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyMembershipFk")
                        .HasColumnType("bigint");

                    b.Property<long?>("ComponentFk")
                        .HasColumnType("bigint");

                    b.Property<long>("ModuleFk")
                        .HasColumnType("bigint");

                    b.Property<long>("PageFk")
                        .HasColumnType("bigint");

                    b.Property<string>("PropertyValue")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_CompanyMembershipPermissions_1");

                    b.HasIndex(new[] { "CompanyMembershipFk" }, "IX_CompanyMembershipPermissions");

                    b.ToTable("CompanyMembershipPermissions");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Component", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<string>("DefaultPropertyValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObjectPropertyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("PageFk")
                        .HasColumnType("bigint");

                    b.Property<long?>("PositionIndex")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_PageComponents");

                    b.HasIndex("ApplicationFk");

                    b.HasIndex("PageFk");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UtcHoursDifference")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Culture", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CountryFk")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageFk")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryFk");

                    b.HasIndex("LanguageFk");

                    b.ToTable("Cultures");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.CultureTranslation", b =>
                {
                    b.Property<string>("CultureFk")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TranslationKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<string>("TranslationValue")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CultureFk", "TranslationKey");

                    b.HasIndex(new[] { "ApplicationFk" }, "IX_CultureTranslations");

                    b.ToTable("CultureTranslations");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ListItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("ListItemGroupFk")
                        .HasColumnType("bigint");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListItemGroupFk");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ListItemGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSystemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_ListItemGroup");

                    b.ToTable("ListItemGroups");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.MembershipType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Memberships");

                    b.ToTable("MembershipTypes");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.MembersipPriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("LastIncreasePercentage")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<long>("MembershipTypeFk")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.HasIndex("MembershipTypeFk");

                    b.ToTable("MembersipPriceHistory", (string)null);
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Module", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsApi")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long?>("PositionIndex")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationFk");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bcc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("BCC");

                    b.Property<string>("Cc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CC");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CultureFk")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NotificationTemplateGroupFk")
                        .HasColumnType("bigint");

                    b.Property<long>("NotificationTypeFk")
                        .HasColumnType("bigint");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id")
                        .HasName("PK_NotificationTraces");

                    b.HasIndex("CompanyFk");

                    b.HasIndex("CultureFk");

                    b.HasIndex("NotificationTypeFk");

                    b.HasIndex("NotificationTemplateGroupFk", "CultureFk");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.NotificationTemplate", b =>
                {
                    b.Property<long>("NotificationTemplateGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("CultureFk")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsHtml")
                        .HasColumnType("bit");

                    b.Property<string>("MessageTemplateText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SubjectTemplateText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationTemplateGroupId", "CultureFk");

                    b.HasIndex("CultureFk");

                    b.ToTable("NotificationTemplates");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Page", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsApi")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<long>("ModuleFk")
                        .HasColumnType("bigint");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long?>("PositionIndex")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_PagesModules");

                    b.HasIndex("ApplicationFk");

                    b.HasIndex("ModuleFk");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<long?>("LastUpdateByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Roles_1");

                    b.HasIndex("CompanyFk");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.RolePermission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("ApplicationFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long?>("ComponentFk")
                        .HasColumnType("bigint");

                    b.Property<long>("ModuleFk")
                        .HasColumnType("bigint");

                    b.Property<long>("PageFk")
                        .HasColumnType("bigint");

                    b.Property<string>("PropertyValue")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<long>("RoleFk")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_UserRolePermissions");

                    b.HasIndex("ComponentFk");

                    b.HasIndex("ModuleFk");

                    b.HasIndex("PageFk");

                    b.HasIndex("RoleFk");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Sequence", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long>("SequenceIndex")
                        .HasColumnType("bigint");

                    b.Property<string>("SequenceName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("TextFormat")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyFk");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("ActivationEmailSent")
                        .HasColumnType("bit");

                    b.Property<Guid>("ActivationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<long>("CompanyFk")
                        .HasColumnType("bigint");

                    b.Property<long?>("CreatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<bool>("EmailValidated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LockedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequirePasswordChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<long>("RoleFk")
                        .HasColumnType("bigint");

                    b.Property<long?>("UpdatedByUserFk")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyFk");

                    b.HasIndex("RoleFk");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.VwGetAllCompanyPermission", b =>
                {
                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ApplicationIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyMembershipFk")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyMembershipPermissionsId")
                        .HasColumnType("bigint");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ComponentFk")
                        .HasColumnType("bigint");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ModuleIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PageIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.ToTable((string)null);

                    b.ToView("Vw_GetAllCompanyPermissions", (string)null);
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.VwGetCompanyMembership", b =>
                {
                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ApplicationIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<bool>("CompanyIsActive")
                        .HasColumnType("bit");

                    b.Property<long>("CompanyMemberShipId")
                        .HasColumnType("bigint");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryFk")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("DefaultCultureFk")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsSystemCompany")
                        .HasColumnType("bit");

                    b.Property<long>("MembershipTypeFk")
                        .HasColumnType("bigint");

                    b.Property<bool>("MembershipTypeIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MembershipTypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.ToTable((string)null);

                    b.ToView("Vw_GetCompanyMemberships", (string)null);
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.VwGetRolePermission", b =>
                {
                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ApplicationIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("ComponentFk")
                        .HasColumnType("bigint");

                    b.Property<long>("ModuleId")
                        .HasColumnType("bigint");

                    b.Property<bool>("ModuleIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long>("PageId")
                        .HasColumnType("bigint");

                    b.Property<bool>("PageIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.Property<long>("RoleFk")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long>("RolePermissionsId")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("Vw_GetRolePermissions", (string)null);
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ActivityLog", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.ListItem", "ActionTypeFkNavigation")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ActionTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_ActivityLogs_ListItems");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.User", "UserFkNavigation")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserFk")
                        .IsRequired()
                        .HasConstraintName("FK_ActivityLogs_Users");

                    b.Navigation("ActionTypeFkNavigation");

                    b.Navigation("UserFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Company", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Country", "CountryFkNavigation")
                        .WithMany("Companies")
                        .HasForeignKey("CountryFk")
                        .IsRequired()
                        .HasConstraintName("FK_Companies_Countries");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Culture", "DefaultCultureFkNavigation")
                        .WithMany("Companies")
                        .HasForeignKey("DefaultCultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_Companies_Cultures");

                    b.Navigation("CountryFkNavigation");

                    b.Navigation("DefaultCultureFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.CompanyMembership", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Application", "ApplicationFkNavigation")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyMemberships_Applications");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Company", "CompanyFkNavigation")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyMemberships_Companies");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.MembershipType", "MembershipTypeFkNavigation")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("MembershipTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyMemberships_Memberships");

                    b.Navigation("ApplicationFkNavigation");

                    b.Navigation("CompanyFkNavigation");

                    b.Navigation("MembershipTypeFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.CompanyMembershipPermission", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.CompanyMembership", "CompanyMembershipFkNavigation")
                        .WithMany("CompanyMembershipPermissions")
                        .HasForeignKey("CompanyMembershipFk")
                        .HasPrincipalKey("Id")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyMembershipPermissions_CompanyMemberships");

                    b.Navigation("CompanyMembershipFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Component", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Application", "ApplicationFkNavigation")
                        .WithMany("Components")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_Components_Applications");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Page", "PageFkNavigation")
                        .WithMany("Components")
                        .HasForeignKey("PageFk")
                        .IsRequired()
                        .HasConstraintName("FK_PageComponents_ModulePages");

                    b.Navigation("ApplicationFkNavigation");

                    b.Navigation("PageFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Culture", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Country", "CountryFkNavigation")
                        .WithMany("Cultures")
                        .HasForeignKey("CountryFk")
                        .IsRequired()
                        .HasConstraintName("FK_Cultures_Countries");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Language", "LanguageFkNavigation")
                        .WithMany("Cultures")
                        .HasForeignKey("LanguageFk")
                        .IsRequired()
                        .HasConstraintName("FK_Cultures_Languages");

                    b.Navigation("CountryFkNavigation");

                    b.Navigation("LanguageFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.CultureTranslation", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Application", "ApplicationFkNavigation")
                        .WithMany("CultureTranslations")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_CultureTranslations_Applications");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Culture", "CultureFkNavigation")
                        .WithMany("CultureTranslations")
                        .HasForeignKey("CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_CultureTranslations_Cultures");

                    b.Navigation("ApplicationFkNavigation");

                    b.Navigation("CultureFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ListItem", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.ListItemGroup", "ListItemGroupFkNavigation")
                        .WithMany("ListItems")
                        .HasForeignKey("ListItemGroupFk")
                        .IsRequired()
                        .HasConstraintName("FK_ListItems_ListItemGroup");

                    b.Navigation("ListItemGroupFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.MembersipPriceHistory", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.MembershipType", "MembershipTypeFkNavigation")
                        .WithMany("MembersipPriceHistories")
                        .HasForeignKey("MembershipTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_MembersipPriceHistory_Memberships");

                    b.Navigation("MembershipTypeFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Module", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Application", "ApplicationFkNavigation")
                        .WithMany("Modules")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_Modules_Applications");

                    b.Navigation("ApplicationFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Notification", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Company", "CompanyFkNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Companies");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Culture", "CultureFkNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_NotificationTraces_Cultures");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.ListItem", "NotificationTypeFkNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_ListItems");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.NotificationTemplate", "NotificationTemplate")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTemplateGroupFk", "CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_NotificationTemplates");

                    b.Navigation("CompanyFkNavigation");

                    b.Navigation("CultureFkNavigation");

                    b.Navigation("NotificationTemplate");

                    b.Navigation("NotificationTypeFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.NotificationTemplate", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Culture", "CultureFkNavigation")
                        .WithMany("NotificationTemplates")
                        .HasForeignKey("CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_NotificationTemplates_Cultures");

                    b.Navigation("CultureFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Page", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Application", "ApplicationFkNavigation")
                        .WithMany("Pages")
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_Pages_Applications");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Module", "ModuleFkNavigation")
                        .WithMany("Pages")
                        .HasForeignKey("ModuleFk")
                        .IsRequired()
                        .HasConstraintName("FK_ModulePages_Modules");

                    b.Navigation("ApplicationFkNavigation");

                    b.Navigation("ModuleFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Role", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Company", "CompanyFkNavigation")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Roles_Companies");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.User", "CompanyFk1")
                        .WithMany("Roles")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Roles_Users");

                    b.Navigation("CompanyFk1");

                    b.Navigation("CompanyFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.RolePermission", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Component", "ComponentFkNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ComponentFk")
                        .HasConstraintName("FK_UserRolePermissions_Components");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Module", "ModuleFkNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ModuleFk")
                        .IsRequired()
                        .HasConstraintName("FK_UserRolePermissions_Modules");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Page", "PageFkNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PageFk")
                        .IsRequired()
                        .HasConstraintName("FK_UserRolePermissions_Pages");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Role", "RoleFkNavigation")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleFk")
                        .IsRequired()
                        .HasConstraintName("FK_UserRolePermissions_Roles");

                    b.Navigation("ComponentFkNavigation");

                    b.Navigation("ModuleFkNavigation");

                    b.Navigation("PageFkNavigation");

                    b.Navigation("RoleFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Sequence", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Company", "CompanyFkNavigation")
                        .WithMany("Sequences")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Sequences_Companies");

                    b.Navigation("CompanyFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.User", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Company", "CompanyFkNavigation")
                        .WithMany("Users")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Companies");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Role", "RoleFkNavigation")
                        .WithMany("Users")
                        .HasForeignKey("RoleFk")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("CompanyFkNavigation");

                    b.Navigation("RoleFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Application", b =>
                {
                    b.Navigation("CompanyMemberships");

                    b.Navigation("Components");

                    b.Navigation("CultureTranslations");

                    b.Navigation("Modules");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Company", b =>
                {
                    b.Navigation("CompanyMemberships");

                    b.Navigation("Notifications");

                    b.Navigation("Roles");

                    b.Navigation("Sequences");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.CompanyMembership", b =>
                {
                    b.Navigation("CompanyMembershipPermissions");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Component", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Country", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Cultures");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Culture", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("CultureTranslations");

                    b.Navigation("NotificationTemplates");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Language", b =>
                {
                    b.Navigation("Cultures");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ListItem", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ListItemGroup", b =>
                {
                    b.Navigation("ListItems");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.MembershipType", b =>
                {
                    b.Navigation("CompanyMemberships");

                    b.Navigation("MembersipPriceHistories");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Module", b =>
                {
                    b.Navigation("Pages");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.NotificationTemplate", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Page", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
