// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vito.Transverse.Identity.DAL.DataBaseContext;

#nullable disable

namespace Vito.Transverse.Identity.DAL.Migrations
{
    [DbContext(typeof(DataBaseServiceContext))]
    partial class DataBaseServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CompanyApplication", b =>
                {
                    b.Property<Guid>("ApplicationFk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<Guid>("CompanyFk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.HasKey("ApplicationFk", "CompanyFk");

                    b.HasIndex("CompanyFk");

                    b.ToTable("CompanyApplications", (string)null);
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ActivityLog", b =>
                {
                    b.Property<long>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TraceId"));

                    b.Property<long>("ActionTypeFk")
                        .HasColumnType("bigint");

                    b.Property<string>("AddtionalInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ApplicationFk")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("CompanyFk")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CultureId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("datetime");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("UserFk")
                        .HasColumnType("bigint");

                    b.HasKey("TraceId")
                        .HasName("PK_UserTraces");

                    b.HasIndex("ActionTypeFk");

                    b.HasIndex("UserFk");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Secret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.HasKey("Id")
                        .HasName("PK_Applications_1");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("CountryFk")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("DefaultCultureFk")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystemCompany")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("Secret")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CountryFk");

                    b.HasIndex("DefaultCultureFk");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Component", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("PageFk")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_PageComponents");

                    b.HasIndex("PageFk");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UtcHoursDifference")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Culture", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("CountryFk")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("LanguageFk")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CountryFk");

                    b.HasIndex("LanguageFk");

                    b.ToTable("Cultures");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.CultureTranslation", b =>
                {
                    b.Property<string>("CultureFk")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("TranslationKey")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TranslationValue")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CultureFk", "TranslationKey");

                    b.ToTable("CultureTranslations");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ListItem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("ListItemGroupFk")
                        .HasColumnType("bigint");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ListItemGroupFk");

                    b.ToTable("ListItems");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ListItemGroup", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsSystemType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ListItemGroup", (string)null);
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Module", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bcc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("BCC");

                    b.Property<string>("Cc")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CC");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CultureFk")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSent")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("NotificationTemplateGroupFk")
                        .HasColumnType("bigint");

                    b.Property<long>("NotificationTypeFk")
                        .HasColumnType("bigint");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id")
                        .HasName("PK_NotificationTraces");

                    b.HasIndex("CultureFk");

                    b.HasIndex("NotificationTypeFk");

                    b.HasIndex("NotificationTemplateGroupFk", "CultureFk");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.NotificationTemplate", b =>
                {
                    b.Property<long>("NotificationTemplateGroupId")
                        .HasColumnType("bigint");

                    b.Property<string>("CultureFk")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsHtml")
                        .HasColumnType("bit");

                    b.Property<string>("MessageTemplateText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("SubjectTemplateText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationTemplateGroupId", "CultureFk");

                    b.HasIndex("CultureFk");

                    b.ToTable("NotificationTemplates");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Page", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("ModuleFk")
                        .HasColumnType("bigint");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK_PagesModules");

                    b.HasIndex("ModuleFk");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("CompanyFk")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DocumentTypeFk")
                        .HasColumnType("bigint");

                    b.Property<string>("DocumentValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<long>("GenderFk")
                        .HasColumnType("bigint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.Property<string>("MobileNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("CompanyFk");

                    b.HasIndex("DocumentTypeFk");

                    b.HasIndex("GenderFk");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Role", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("NameTranslationKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id")
                        .HasName("PK_Roles_1");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("ActivationEmailSent")
                        .HasColumnType("bit");

                    b.Property<Guid>("ActivationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyFk")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EmailValidated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastAccess")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LockedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PersonFk")
                        .HasColumnType("bigint");

                    b.Property<bool>("RequirePasswordChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<long>("RoleFk")
                        .HasColumnType("bigint");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyFk");

                    b.HasIndex("PersonFk");

                    b.HasIndex("RoleFk");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.UserRolePermission", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long?>("ComponentFk")
                        .HasColumnType("bigint");

                    b.Property<bool?>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<long>("ModuleFk")
                        .HasColumnType("bigint");

                    b.Property<long?>("PageFk")
                        .HasColumnType("bigint");

                    b.Property<long>("UserRoleFk")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ComponentFk");

                    b.HasIndex("ModuleFk");

                    b.HasIndex("PageFk");

                    b.HasIndex("UserRoleFk");

                    b.ToTable("UserRolePermissions");
                });

            modelBuilder.Entity("CompanyApplication", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationFk")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyApplications_Applications");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_CompanyApplications_Companies");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ActivityLog", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.ListItem", "ActionTypeFkNavigation")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ActionTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_ActivityLogs_ListItems");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.User", "UserFkNavigation")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserFk")
                        .IsRequired()
                        .HasConstraintName("FK_UserTraces_Users");

                    b.Navigation("ActionTypeFkNavigation");

                    b.Navigation("UserFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Company", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Country", "CountryFkNavigation")
                        .WithMany("Companies")
                        .HasForeignKey("CountryFk")
                        .IsRequired()
                        .HasConstraintName("FK_Companies_Countries");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Culture", "DefaultCultureFkNavigation")
                        .WithMany("Companies")
                        .HasForeignKey("DefaultCultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_Companies_Cultures");

                    b.Navigation("CountryFkNavigation");

                    b.Navigation("DefaultCultureFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Component", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Page", "PageFkNavigation")
                        .WithMany("Components")
                        .HasForeignKey("PageFk")
                        .IsRequired()
                        .HasConstraintName("FK_PageComponents_ModulePages");

                    b.Navigation("PageFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Culture", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Country", "CountryFkNavigation")
                        .WithMany("Cultures")
                        .HasForeignKey("CountryFk")
                        .IsRequired()
                        .HasConstraintName("FK_Cultures_Countries");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Language", "LanguageFkNavigation")
                        .WithMany("Cultures")
                        .HasForeignKey("LanguageFk")
                        .IsRequired()
                        .HasConstraintName("FK_Cultures_Languages");

                    b.Navigation("CountryFkNavigation");

                    b.Navigation("LanguageFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.CultureTranslation", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Culture", "CultureFkNavigation")
                        .WithMany("CultureTranslations")
                        .HasForeignKey("CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_CultureTranslations_Cultures");

                    b.Navigation("CultureFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ListItem", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.ListItemGroup", "ListItemGroupFkNavigation")
                        .WithMany("ListItems")
                        .HasForeignKey("ListItemGroupFk")
                        .IsRequired()
                        .HasConstraintName("FK_ListItems_ListItemGroup");

                    b.Navigation("ListItemGroupFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Notification", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Culture", "CultureFkNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_NotificationTraces_Cultures");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.ListItem", "NotificationTypeFkNavigation")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_ListItems");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.NotificationTemplate", "NotificationTemplate")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTemplateGroupFk", "CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_NotificationTemplates");

                    b.Navigation("CultureFkNavigation");

                    b.Navigation("NotificationTemplate");

                    b.Navigation("NotificationTypeFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.NotificationTemplate", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Culture", "CultureFkNavigation")
                        .WithMany("NotificationTemplates")
                        .HasForeignKey("CultureFk")
                        .IsRequired()
                        .HasConstraintName("FK_NotificationTemplates_Cultures");

                    b.Navigation("CultureFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Page", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Module", "ModuleFkNavigation")
                        .WithMany("Pages")
                        .HasForeignKey("ModuleFk")
                        .IsRequired()
                        .HasConstraintName("FK_ModulePages_Modules");

                    b.Navigation("ModuleFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Person", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Company", "CompanyFkNavigation")
                        .WithMany("People")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Persons_Companies");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.ListItem", "DocumentTypeFkNavigation")
                        .WithMany("PersonDocumentTypeFkNavigations")
                        .HasForeignKey("DocumentTypeFk")
                        .IsRequired()
                        .HasConstraintName("FK_Persons_ListItems");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.ListItem", "GenderFkNavigation")
                        .WithMany("PersonGenderFkNavigations")
                        .HasForeignKey("GenderFk")
                        .IsRequired()
                        .HasConstraintName("FK_Persons_ListItems1");

                    b.Navigation("CompanyFkNavigation");

                    b.Navigation("DocumentTypeFkNavigation");

                    b.Navigation("GenderFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.User", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Company", "CompanyFkNavigation")
                        .WithMany("Users")
                        .HasForeignKey("CompanyFk")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Companies");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Person", "PersonFkNavigation")
                        .WithMany("Users")
                        .HasForeignKey("PersonFk")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Persons");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Role", "RoleFkNavigation")
                        .WithMany("Users")
                        .HasForeignKey("RoleFk")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("CompanyFkNavigation");

                    b.Navigation("PersonFkNavigation");

                    b.Navigation("RoleFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.UserRolePermission", b =>
                {
                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Component", "ComponentFkNavigation")
                        .WithMany("UserRolePermissions")
                        .HasForeignKey("ComponentFk")
                        .HasConstraintName("FK_UserRolePermissions_Components");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Module", "ModuleFkNavigation")
                        .WithMany("UserRolePermissions")
                        .HasForeignKey("ModuleFk")
                        .IsRequired()
                        .HasConstraintName("FK_UserRolePermissions_Modules");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Page", "PageFkNavigation")
                        .WithMany("UserRolePermissions")
                        .HasForeignKey("PageFk")
                        .HasConstraintName("FK_UserRolePermissions_Pages");

                    b.HasOne("Vito.Transverse.Identity.Domain.Models.Role", "UserRoleFkNavigation")
                        .WithMany("UserRolePermissions")
                        .HasForeignKey("UserRoleFk")
                        .IsRequired()
                        .HasConstraintName("FK_UserRolePermissions_Roles");

                    b.Navigation("ComponentFkNavigation");

                    b.Navigation("ModuleFkNavigation");

                    b.Navigation("PageFkNavigation");

                    b.Navigation("UserRoleFkNavigation");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Company", b =>
                {
                    b.Navigation("People");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Component", b =>
                {
                    b.Navigation("UserRolePermissions");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Country", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Cultures");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Culture", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("CultureTranslations");

                    b.Navigation("NotificationTemplates");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Language", b =>
                {
                    b.Navigation("Cultures");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ListItem", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Notifications");

                    b.Navigation("PersonDocumentTypeFkNavigations");

                    b.Navigation("PersonGenderFkNavigations");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.ListItemGroup", b =>
                {
                    b.Navigation("ListItems");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Module", b =>
                {
                    b.Navigation("Pages");

                    b.Navigation("UserRolePermissions");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.NotificationTemplate", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Page", b =>
                {
                    b.Navigation("Components");

                    b.Navigation("UserRolePermissions");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Person", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.Role", b =>
                {
                    b.Navigation("UserRolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Vito.Transverse.Identity.Domain.Models.User", b =>
                {
                    b.Navigation("ActivityLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
