//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IClient {

    getApiHomeV0_9Ping(): Promise<PingResponseDTO>;

    getApiHomeV1Detect(): Promise<PingResponseDTO>;

    getApiHomeV1Ping(): Promise<PingResponseDTO>;

    postApiOauth2V1Token(requestBody: TokenRequestDTO): Promise<TokenResponseDTO>;

    getApiLocalizationV1AllLocalizedMessages(): Promise<CultureTranslationDTO[]>;

    getApiLocalizationV1LocalizedMessage(localizationMessageKey: string, parameters: string[] | null | undefined): Promise<CultureTranslationDTO>;

    getApiCultureV1UtcNow(): Promise<Date>;

    getApiCultureV1ActiveCultureList(): Promise<CultureDTO[]>;

    getApiCultureV1ActiveCultureListItemDTOList(): Promise<ListItemDTO[]>;

    getApiTwilioV1SendSMS(message: string): Promise<PingResponseDTO>;
}

export class Client implements IClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    getApiHomeV0_9Ping(): Promise<PingResponseDTO> {
        let url_ = this.baseUrl + "/api/Home/v0.9/Ping";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetApiHomeV0_9Ping(_response);
        });
    }

    protected processGetApiHomeV0_9Ping(response: Response): Promise<PingResponseDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PingResponseDTO;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PingResponseDTO>(null as any);
    }

    getApiHomeV1Detect(): Promise<PingResponseDTO> {
        let url_ = this.baseUrl + "/api/Home/v1/Detect";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetApiHomeV1Detect(_response);
        });
    }

    protected processGetApiHomeV1Detect(response: Response): Promise<PingResponseDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PingResponseDTO;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PingResponseDTO>(null as any);
    }

    getApiHomeV1Ping(): Promise<PingResponseDTO> {
        let url_ = this.baseUrl + "/api/Home/v1/Ping";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetApiHomeV1Ping(_response);
        });
    }

    protected processGetApiHomeV1Ping(response: Response): Promise<PingResponseDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PingResponseDTO;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PingResponseDTO>(null as any);
    }

    postApiOauth2V1Token(requestBody: TokenRequestDTO): Promise<TokenResponseDTO> {
        let url_ = this.baseUrl + "/api/Oauth2/v1/Token";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(requestBody);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPostApiOauth2V1Token(_response);
        });
    }

    protected processPostApiOauth2V1Token(response: Response): Promise<TokenResponseDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as TokenResponseDTO;
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HttpValidationProblemDetails;
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TokenResponseDTO>(null as any);
    }

    getApiLocalizationV1AllLocalizedMessages(): Promise<CultureTranslationDTO[]> {
        let url_ = this.baseUrl + "/api/Localization/v1/AllLocalizedMessagesAsync";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetApiLocalizationV1AllLocalizedMessages(_response);
        });
    }

    protected processGetApiLocalizationV1AllLocalizedMessages(response: Response): Promise<CultureTranslationDTO[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CultureTranslationDTO[];
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HttpValidationProblemDetails;
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CultureTranslationDTO[]>(null as any);
    }

    getApiLocalizationV1LocalizedMessage(localizationMessageKey: string, parameters: string[] | null | undefined): Promise<CultureTranslationDTO> {
        let url_ = this.baseUrl + "/api/Localization/v1/LocalizedMessage?";
        if (localizationMessageKey === undefined || localizationMessageKey === null)
            throw new Error("The parameter 'localizationMessageKey' must be defined and cannot be null.");
        else
            url_ += "localizationMessageKey=" + encodeURIComponent("" + localizationMessageKey) + "&";
        if (parameters !== undefined && parameters !== null)
            parameters && parameters.forEach(item => { url_ += "parameters=" + encodeURIComponent("" + item) + "&"; });
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetApiLocalizationV1LocalizedMessage(_response);
        });
    }

    protected processGetApiLocalizationV1LocalizedMessage(response: Response): Promise<CultureTranslationDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CultureTranslationDTO;
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HttpValidationProblemDetails;
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CultureTranslationDTO>(null as any);
    }

    getApiCultureV1UtcNow(): Promise<Date> {
        let url_ = this.baseUrl + "/api/Culture/v1/UtcNow";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetApiCultureV1UtcNow(_response);
        });
    }

    protected processGetApiCultureV1UtcNow(response: Response): Promise<Date> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as Date;
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HttpValidationProblemDetails;
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<Date>(null as any);
    }

    getApiCultureV1ActiveCultureList(): Promise<CultureDTO[]> {
        let url_ = this.baseUrl + "/api/Culture/v1/ActiveCultureListAsync";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetApiCultureV1ActiveCultureList(_response);
        });
    }

    protected processGetApiCultureV1ActiveCultureList(response: Response): Promise<CultureDTO[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as CultureDTO[];
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HttpValidationProblemDetails;
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CultureDTO[]>(null as any);
    }

    getApiCultureV1ActiveCultureListItemDTOList(): Promise<ListItemDTO[]> {
        let url_ = this.baseUrl + "/api/Culture/v1/ActiveCultureListItemDTOListAsync";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetApiCultureV1ActiveCultureListItemDTOList(_response);
        });
    }

    protected processGetApiCultureV1ActiveCultureListItemDTOList(response: Response): Promise<ListItemDTO[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as ListItemDTO[];
            return result200;
            });
        } else if (status === 404) {
            return response.text().then((_responseText) => {
            return throwException("A server side error occurred.", status, _responseText, _headers);
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            result400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HttpValidationProblemDetails;
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ListItemDTO[]>(null as any);
    }

    getApiTwilioV1SendSMS(message: string): Promise<PingResponseDTO> {
        let url_ = this.baseUrl + "/api/Twilio/v1/SendSMS?";
        if (message === undefined || message === null)
            throw new Error("The parameter 'message' must be defined and cannot be null.");
        else
            url_ += "message=" + encodeURIComponent("" + message) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetApiTwilioV1SendSMS(_response);
        });
    }

    protected processGetApiTwilioV1SendSMS(response: Response): Promise<PingResponseDTO> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as PingResponseDTO;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PingResponseDTO>(null as any);
    }
}

export interface PingResponseDTO {
    pingDate?: Date | undefined;
    pingMessage?: string | undefined;
    deviceInformation?: DeviceInformationDTO;
}

export interface DeviceInformationDTO {
}

export interface TokenResponseDTO {
    access_token?: string | undefined;
    token_type?: string | undefined;
    issued_at?: number | undefined;
    expires_in?: number | undefined;
    status?: string | undefined;
    scope?: string | undefined;
    application_id?: string | undefined;
    company_id?: string | undefined;
    user_id?: string | undefined;
    user_avatar?: string | undefined;
}

export interface ProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export interface HttpValidationProblemDetails extends ProblemDetails {
    errors?: { [key: string]: string[]; };

    [key: string]: any;
}

export interface TokenRequestDTO {
    grant_type?: string;
    scope?: string | undefined;
    application_id?: string;
    application_secret?: string;
    company_id?: string;
    company_secret?: string;
    user_id?: string | undefined;
    user_secret?: string | undefined;
    refresh_token?: string | undefined;
}

export interface CultureTranslationDTO {
    cultureFk?: string;
    translationKey?: string;
    translationValue?: string;
}

export interface CultureDTO {
    id?: string;
    nameTranslationKey?: string;
    countryFk?: string | undefined;
    languageFk?: string | undefined;
    isEnabled?: boolean;
    name?: string;
}

export interface ListItemDTO {
    listItemGroupFk?: string;
    id?: string;
    nameTranslationKey?: string;
    orderIndex?: number | undefined;
    isEnabled?: boolean;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new ApiException(message, status, response, headers, result);
}