@Vito.Transverse.Identity.Api_HostAddress = http://localhost:5237

### Home ###

### Ping

GET {{Vito.Transverse.Identity.Api_HostAddress}}/Home/v1/Ping
Accept: application/json

### Detect


GET {{Vito.Transverse.Identity.Api_HostAddress}}/api/Home/v1/Detect

### Twilio ###

### SendSMS

GET {{Vito.Transverse.Identity.Api_HostAddress}}/api/Twilio/v1/SendSMS?message=string

### Oauth2 ###



###  1 ActionType_LoginFail_CompanyNotFound

POST {{Vito.Transverse.Identity.Api_HostAddress}}/api/Oauth2/v1/Token
Content-Type: application/json
 {
  "grant_type": "AuthorizationCode",
  "scope": "",
  "application_id": "eb2d4ffc-dc34-435f-8983-ecd42481143f",
  "application_secret": "ce09510a-7c12-4121-9f8b-ca0506ca302c",
  "company_id": "9973FD8B-4351-4572-BEFE-A08A76A1FF1B",
  "company_secret": "8010e5e4-5f3f-4cd9-9d4c-b9babbecc740",
  "user_id": "",
  "user_secret": "",
  "refresh_token": ""
}

### - 2 ActionType_LoginFail_CompanySecretInvalid

POST {{Vito.Transverse.Identity.Api_HostAddress}}/api/Oauth2/v1/Token
Content-Type: application/json
 {
  "grant_type": "AuthorizationCode",
  "scope": "",
  "application_id": "eb2d4ffc-dc34-435f-8983-ecd42481143f",
  "application_secret": "ce09510a-7c12-4121-9f8b-ca0506ca302c",
  "company_id": "55c26aaf-79b0-42e9-9adc-1f3fcba6d6d8",
  "company_secret": "9973FD8B-4351-4572-BEFE-A08A76A1FF1B",
  "user_id": "ever.torresg",
  "user_secret": "123",
  "refresh_token": ""
}


###  - 3 -  ActionType_LoginFail_ApplicationNoFound
POST {{Vito.Transverse.Identity.Api_HostAddress}}/api/Oauth2/v1/Token
Content-Type: application/json

 {
  "grant_type": "AuthorizationCode",
  "scope": "",
  "application_id": "9973FD8B-4351-4572-BEFE-A08A76A1FF1B",
  "application_secret": "ce09510a-7c12-4121-9f8b-ca0506ca302c",
  "company_id": "c5bcea98-2974-4d43-8110-28d402cf5ce2",
  "company_secret": "8010e5e4-5f3f-4cd9-9d4c-b9babbecc740",
  "user_id": "",
  "user_secret": "",
  "refresh_token": ""
}
  
###   4  ActionType_LoginFail_ApplicationSecretInvalid 

POST {{Vito.Transverse.Identity.Api_HostAddress}}/api/Oauth2/v1/Token
Content-Type: application/json

 {
  "grant_type": "AuthorizationCode",
  "scope": "",
  "application_id": "eb2d4ffc-dc34-435f-8983-ecd42481143f",
  "application_secret": "9973FD8B-4351-4572-BEFE-A08A76A1FF1B",
  "company_id": "55c26aaf-79b0-42e9-9adc-1f3fcba6d6d8",
  "company_secret": "ba3a564f-946a-4b07-b44c-bf8ea21e808c",
  "user_id": "",
  "user_secret": "",
  "refresh_token": ""
}



### 5 - ActionType_LoginFail_UserNotFound
POST {{Vito.Transverse.Identity.Api_HostAddress}}/api/Oauth2/v1/Token
Content-Type: application/json

 {
  "grant_type": "ClientCredentials",
  "scope": "",
  "application_id": "eb2d4ffc-dc34-435f-8983-ecd42481143f",
  "application_secret": "ce09510a-7c12-4121-9f8b-ca0506ca302c",
  "company_id": "55c26aaf-79b0-42e9-9adc-1f3fcba6d6d8",
  "company_secret": "ba3a564f-946a-4b07-b44c-bf8ea21e808c",
  "user_id": "ever.torresg1",
  "user_secret": "123",
  "refresh_token": ""
}

###  6 - ActionType_LoginFail_UserSecretInvalid
POST {{Vito.Transverse.Identity.Api_HostAddress}}/api/Oauth2/v1/Token
Content-Type: application/json

 {
  "grant_type": "ClientCredentials",
  "scope": "",
  "application_id": "eb2d4ffc-dc34-435f-8983-ecd42481143f",
  "application_secret": "ce09510a-7c12-4121-9f8b-ca0506ca302c",
  "company_id": "55c26aaf-79b0-42e9-9adc-1f3fcba6d6d8",
  "company_secret": "ba3a564f-946a-4b07-b44c-bf8ea21e808c",
  "user_id": "ever.torresg",
  "user_secret": "1234",
  "refresh_token": ""
}

### 7 -  ActionType_LoginSuccessByAuthorizarionCode
POST {{Vito.Transverse.Identity.Api_HostAddress}}/api/Oauth2/v1/Token
Content-Type: application/json

 {
  "grant_type": "AuthorizationCode",
  "scope": "",
  "application_id": "eb2d4ffc-dc34-435f-8983-ecd42481143f",
  "application_secret": "ce09510a-7c12-4121-9f8b-ca0506ca302c",
  "company_id": "55c26aaf-79b0-42e9-9adc-1f3fcba6d6d8",
  "company_secret": "ba3a564f-946a-4b07-b44c-bf8ea21e808c",
  "user_id": "",
  "user_secret": "",
  "refresh_token": ""
}

### 8 -ActionType_LoginSuccessByClientCredentials

POST {{Vito.Transverse.Identity.Api_HostAddress}}/api/Oauth2/v1/Token
Content-Type: application/json

 {
  "grant_type": "ClientCredentials",
  "scope": "",
  "application_id": "eb2d4ffc-dc34-435f-8983-ecd42481143f",
  "application_secret": "ce09510a-7c12-4121-9f8b-ca0506ca302c",
  "company_id": "55c26aaf-79b0-42e9-9adc-1f3fcba6d6d8",
  "company_secret": "ba3a564f-946a-4b07-b44c-bf8ea21e808c",
  "user_id": "ever.torresg",
  "user_secret": "123",
  "refresh_token": ""
}